# Generated by Django 4.2.3 on 2023-07-13 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0005_alter_mytodo_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytodo',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
